# Install/pull two Ollama models for SentinelOps VAPT (draft + refine cascade).
# Detects ollama.exe on PATH or common install locations. Writes .env snippet under repo root.
# Usage: .\scripts\setup-local-llm.ps1
# Optional env before run: $env:SENTINELOPS_LLM_DRAFT_MODEL / $env:SENTINELOPS_LLM_MODEL
$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir "..")).Path
$logDir = Join-Path $RepoRoot "logs"
if (-not (Test-Path $logDir)) { New-Item -ItemType Directory -Path $logDir | Out-Null }
$logFile = Join-Path $logDir ("setup-llm-" + (Get-Date -Format "yyyyMMdd-HHmmss") + ".log")

function Log([string] $m) {
  $line = "[setup-local-llm] $m"
  Write-Host $line
  Add-Content -LiteralPath $logFile -Value $line
}

function Find-OllamaExe {
  if (Get-Command ollama -ErrorAction SilentlyContinue) {
    return (Get-Command ollama).Path
  }
  $pf86 = [Environment]::GetFolderPath("ProgramFilesX86")
  $cands = @(
    (Join-Path $env:LOCALAPPDATA "Programs\Ollama\ollama.exe"),
    (Join-Path $env:ProgramFiles "Ollama\ollama.exe")
  )
  if ($pf86) { $cands += (Join-Path $pf86 "Ollama\ollama.exe") }
  foreach ($p in $cands) {
    if ($p -and (Test-Path -LiteralPath $p)) { return $p }
  }
  return $null
}

$ollama = Find-OllamaExe
if (-not $ollama) {
  Log "ERROR: Ollama not found. Install from https://ollama.com/ and ensure ollama is on PATH, then re-run."
  Log "  On Windows you can also use WSL: bash scripts/setup-local-llm.sh"
  exit 1
}
Log "Using Ollama at: $ollama"
& $ollama --version 2>&1 | ForEach-Object { Log $_ }

$draft = if ($env:SENTINELOPS_LLM_DRAFT_MODEL) { $env:SENTINELOPS_LLM_DRAFT_MODEL } else { "qwen2.5:7b" }
$refine = if ($env:SENTINELOPS_LLM_MODEL) { $env:SENTINELOPS_LLM_MODEL } else { "llama3.1:8b" }

Log "Pulling draft model: $draft …"
& $ollama pull $draft
if ($LASTEXITCODE -ne 0) { throw "ollama pull $draft failed" }

Log "Pulling refine model: $refine …"
& $ollama pull $refine
if ($LASTEXITCODE -ne 0) { throw "ollama pull $refine failed" }

# Auto-rebind Ollama to 0.0.0.0 if a Docker Compose file is present, so the
# backend container can reach it via host.docker.internal. Same logic as the
# .sh path. Set $env:SENTINELOPS_LLM_AUTOBIND=0 to skip.
$composeFileProbe = Join-Path $RepoRoot "infra\docker\docker-compose.yml"
if ((Test-Path -LiteralPath $composeFileProbe) -and ($env:SENTINELOPS_LLM_AUTOBIND -ne "0")) {
  $bindPs1 = Join-Path $ScriptDir "bind-ollama-host.ps1"
  if (Test-Path -LiteralPath $bindPs1) {
    $needRebind = $false
    try {
      $listeners = Get-NetTCPConnection -State Listen -LocalPort 11434 -ErrorAction Stop
      if ($listeners) {
        $hasAny = $false; $hasLoop = $false
        foreach ($c in $listeners) {
          if ($c.LocalAddress -in @("0.0.0.0", "::", "*")) { $hasAny = $true }
          elseif ($c.LocalAddress -in @("127.0.0.1", "::1")) { $hasLoop = $true }
        }
        if ($hasLoop -and -not $hasAny) { $needRebind = $true }
      }
    } catch { }
    if ($needRebind) {
      Log "Ollama is loopback-only — running bind-ollama-host.ps1 to expose it on 0.0.0.0:11434 (set `$env:SENTINELOPS_LLM_AUTOBIND=0 to skip)."
      $oldEa = $ErrorActionPreference
      $ErrorActionPreference = "Continue"
      & $bindPs1 2>&1 | ForEach-Object { Log $_ }
      $ErrorActionPreference = $oldEa
    }
  } else {
    Log "NOTE: $bindPs1 missing; skipping auto-rebind of host Ollama."
  }
}

$hostAddr = if ($env:SENTINELOPS_LLM_OLLAMA_HOST) { $env:SENTINELOPS_LLM_OLLAMA_HOST } else { "127.0.0.1" }
$port = if ($env:SENTINELOPS_LLM_OLLAMA_PORT) { $env:SENTINELOPS_LLM_OLLAMA_PORT } else { "11434" }
$baseHttp = "http://${hostAddr}:$port"
try {
  $r = Invoke-WebRequest -UseBasicParsing -Uri $baseHttp -TimeoutSec 3 -ErrorAction Stop
  Log "Ollama HTTP OK at $baseHttp ($($r.StatusCode))"
} catch {
  Log "NOTE: could not reach $baseHttp — start 'Ollama' app or: ollama serve"
}

$out = Join-Path $RepoRoot ".env.llm.local.generated"
$ts = (Get-Date -Format o)
$apiV1 = "$baseHttp/v1"
$dockerApiV1 = "http://host.docker.internal:$port/v1"

# Pick the right default for the snippet: prefer the Docker URL when this repo
# ships a docker-compose file (the default `make up` dev path).
$composeFile = Join-Path $RepoRoot "infra\docker\docker-compose.yml"
if (Test-Path -LiteralPath $composeFile) {
  $defaultApiV1 = $dockerApiV1
  $altHeader = "# --- Backend runs natively on the host (uvicorn dev) ---"
  $altApiV1 = $apiV1
} else {
  $defaultApiV1 = $apiV1
  $altHeader = "# --- API in Docker + Ollama on host ---"
  $altApiV1 = $dockerApiV1
}

$block = @"
# --- Generated by scripts/setup-local-llm.ps1 at $ts ---
# Repo: $RepoRoot
# Merge into .env. Do not commit .env.
SENTINELOPS_LLM_OLLAMA=1
OPENAI_API_KEY=ollama
SENTINELOPS_LLM_BASE_URL=$defaultApiV1
SENTINELOPS_LLM_DRAFT_MODEL=$draft
SENTINELOPS_LLM_MODEL=$refine
SENTINELOPS_LLM_CASCADE=1
#
$altHeader
# SENTINELOPS_LLM_BASE_URL=$altApiV1
# (Docker on Windows: scripts/bind-ollama-host.ps1 sets OLLAMA_HOST=0.0.0.0:11434 + restarts the app.
#  Linux/WSL: scripts/bind-ollama-host.sh writes a systemd override and restarts ollama.)
"@
Set-Content -LiteralPath $out -Value $block -Encoding UTF8
Log "Wrote: $out"
Log "Log: $logFile"
exit 0
