# Install/pull two Ollama models for SentinelOps VAPT (draft + refine cascade).
# Detects ollama.exe on PATH or common install locations. Writes .env snippet under repo root.
# Usage: .\scripts\setup-local-llm.ps1
# Optional env before run: $env:SENTINELOPS_LLM_DRAFT_MODEL / $env:SENTINELOPS_LLM_MODEL
$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir "..")).Path
$logDir = Join-Path $RepoRoot "logs"
if (-not (Test-Path $logDir)) { New-Item -ItemType Directory -Path $logDir | Out-Null }
$logFile = Join-Path $logDir ("setup-llm-" + (Get-Date -Format "yyyyMMdd-HHmmss") + ".log")

function Log([string] $m) {
  $line = "[setup-local-llm] $m"
  Write-Host $line
  Add-Content -LiteralPath $logFile -Value $line
}

function Find-OllamaExe {
  if (Get-Command ollama -ErrorAction SilentlyContinue) {
    return (Get-Command ollama).Path
  }
  $pf86 = [Environment]::GetFolderPath("ProgramFilesX86")
  $cands = @(
    (Join-Path $env:LOCALAPPDATA "Programs\Ollama\ollama.exe"),
    (Join-Path $env:ProgramFiles "Ollama\ollama.exe")
  )
  if ($pf86) { $cands += (Join-Path $pf86 "Ollama\ollama.exe") }
  foreach ($p in $cands) {
    if ($p -and (Test-Path -LiteralPath $p)) { return $p }
  }
  return $null
}

$ollama = Find-OllamaExe
if (-not $ollama) {
  Log "ERROR: Ollama not found. Install from https://ollama.com/ and ensure ollama is on PATH, then re-run."
  Log "  On Windows you can also use WSL: bash scripts/setup-local-llm.sh"
  exit 1
}
Log "Using Ollama at: $ollama"
& $ollama --version 2>&1 | ForEach-Object { Log $_ }

$draft = if ($env:SENTINELOPS_LLM_DRAFT_MODEL) { $env:SENTINELOPS_LLM_DRAFT_MODEL } else { "qwen2.5:7b" }
$refine = if ($env:SENTINELOPS_LLM_MODEL) { $env:SENTINELOPS_LLM_MODEL } else { "llama3.1:8b" }

Log "Pulling draft model: $draft …"
& $ollama pull $draft
if ($LASTEXITCODE -ne 0) { throw "ollama pull $draft failed" }

Log "Pulling refine model: $refine …"
& $ollama pull $refine
if ($LASTEXITCODE -ne 0) { throw "ollama pull $refine failed" }

$hostAddr = if ($env:SENTINELOPS_LLM_OLLAMA_HOST) { $env:SENTINELOPS_LLM_OLLAMA_HOST } else { "127.0.0.1" }
$port = if ($env:SENTINELOPS_LLM_OLLAMA_PORT) { $env:SENTINELOPS_LLM_OLLAMA_PORT } else { "11434" }
$baseHttp = "http://${hostAddr}:$port"
try {
  $r = Invoke-WebRequest -UseBasicParsing -Uri $baseHttp -TimeoutSec 3 -ErrorAction Stop
  Log "Ollama HTTP OK at $baseHttp ($($r.StatusCode))"
} catch {
  Log "NOTE: could not reach $baseHttp — start 'Ollama' app or: ollama serve"
}

$out = Join-Path $RepoRoot ".env.llm.local.generated"
$ts = (Get-Date -Format o)
$apiV1 = "$baseHttp/v1"
$block = @"
# --- Generated by scripts/setup-local-llm.ps1 at $ts ---
# Repo: $RepoRoot
# Merge into .env. Do not commit .env.
#
SENTINELOPS_LLM_OLLAMA=1
OPENAI_API_KEY=ollama
SENTINELOPS_LLM_BASE_URL=$apiV1
SENTINELOPS_LLM_DRAFT_MODEL=$draft
SENTINELOPS_LLM_MODEL=$refine
SENTINELOPS_LLM_CASCADE=1
#
# API in Docker + Ollama on host: try
# SENTINELOPS_LLM_BASE_URL=http://host.docker.internal:11434/v1
"@
Set-Content -LiteralPath $out -Value $block -Encoding UTF8
Log "Wrote: $out"
Log "Log: $logFile"
exit 0
