#!/usr/bin/env bash
# Install/pull two recommended open-weight models for SentinelOps VAPT (Ollama).
# Detects Ollama on PATH, probes the local API, and writes a repo-local env snippet
# (paths are from this script's location, not hardcoded user dirs).
#
# Usage (WSL / Linux / macOS / Git Bash on Windows):
#   bash scripts/setup-local-llm.sh
#   SENTINELOPS_LLM_DRAFT_MODEL=custom:tag SENTINELOPS_LLM_MODEL=other:tag bash scripts/setup-local-llm.sh
#
# Requires: curl or wget; Ollama from https://ollama.com/ (not bundled here).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_SNIPPET="${REPO_ROOT}/.env.llm.local.generated"
LOG="${REPO_ROOT}/logs/setup-llm-$(date +%Y%m%d-%H%M%S).log"
mkdir -p "${REPO_ROOT}/logs"
exec > >(tee -a "$LOG") 2>&1

log() { echo "[setup-local-llm] $*"; }

detect_ollama() {
  if command -v ollama >/dev/null 2>&1; then
    command -v ollama
    return 0
  fi
  for p in "$HOME/.local/bin/ollama" "/usr/local/bin/ollama" "/opt/homebrew/bin/ollama"; do
    if [[ -x "$p" ]]; then
      echo "$p"
      return 0
    fi
  done
  return 1
}

OLLAMA_BIN="$(detect_ollama || true)"
if [[ -z "${OLLAMA_BIN}" ]]; then
  log "ERROR: Ollama is not on PATH and no common install location matched."
  log "  Install: https://ollama.com/   then re-run this script."
  log "  On Windows, use WSL or run: .\\scripts\\setup-local-llm.ps1"
  exit 1
fi
log "Using Ollama at: $OLLAMA_BIN"
"$OLLAMA_BIN" --version 2>&1 | head -n 2 || true

# Default tags are strong general-purpose local models; override via env when calling this script.
DRAFT_TAG="${SENTINELOPS_LLM_DRAFT_MODEL:-qwen2.5:7b}"
REFINE_TAG="${SENTINELOPS_LLM_MODEL:-llama3.1:8b}"

log "Pulling draft model: $DRAFT_TAG (fast structured pass)…"
"$OLLAMA_BIN" pull "$DRAFT_TAG"

log "Pulling refine model: $REFINE_TAG (executive triage)…"
"$OLLAMA_BIN" pull "$REFINE_TAG"

# Probe API — works when ollama serve is running (often same machine).
OLLAMA_HOST_ADDR="${SENTINELOPS_LLM_OLLAMA_HOST:-127.0.0.1}"
OLLAMA_PORT="${SENTINELOPS_LLM_OLLAMA_PORT:-11434}"
BASE_HTTP="http://${OLLAMA_HOST_ADDR}:${OLLAMA_PORT}"
code=""
if command -v curl >/dev/null 2>&1; then
  code="$(curl -s -o /dev/null -w "%{http_code}" "${BASE_HTTP}/" 2>/dev/null || echo 000)"
else
  code="skip"
fi
if [[ "$code" = "200" ]]; then
  log "Ollama HTTP server responded OK at ${BASE_HTTP}"
else
  log "NOTE: could not confirm HTTP 200 on ${BASE_HTTP} (code=${code})."
  log "  Start the daemon:  ollama serve   (or Ollama Desktop)."
fi

# When the SentinelOps backend runs in Docker on the same host, the bind address
# must NOT be 127.0.0.1 — containers cannot reach a host loopback even with
# `extra_hosts: host-gateway`. Auto-rebind to 0.0.0.0 unless the caller opts out
# (SENTINELOPS_LLM_BIND_ALL=0) or is targeting a remote Ollama.
if [[ "${OLLAMA_HOST_ADDR}" == "127.0.0.1" || "${OLLAMA_HOST_ADDR}" == "localhost" ]]; then
  if [[ "${SENTINELOPS_LLM_BIND_ALL:-1}" == "1" ]]; then
    if ss -ltn 2>/dev/null | awk '{print $4}' | grep -qE "^127\\.0\\.0\\.1:${OLLAMA_PORT}\$"; then
      log "Ollama is bound to 127.0.0.1:${OLLAMA_PORT} — Docker containers cannot reach it."
      log "  Running scripts/bind-ollama-host.sh to bind on 0.0.0.0 (set SENTINELOPS_LLM_BIND_ALL=0 to skip)."
      if bash "${SCRIPT_DIR}/bind-ollama-host.sh"; then
        log "  Rebound. host.docker.internal:${OLLAMA_PORT} should now resolve from containers."
      else
        log "  WARN: bind-ollama-host.sh failed; you may need to run it manually with sudo."
      fi
    fi
  fi
fi

# Base URL for API on this host (uvicorn dev path):
API_V1="${BASE_HTTP}/v1"
# Base URL when the backend runs in Docker on the same host (default in this repo).
DOCKER_API_V1="http://host.docker.internal:${OLLAMA_PORT}/v1"

# Pick the right default for the snippet: prefer the Docker URL when a docker-compose
# file exists in the repo (the supported in-repo dev path is `make up`).
if [[ -f "${REPO_ROOT}/infra/docker/docker-compose.yml" ]]; then
  DEFAULT_API_V1="${DOCKER_API_V1}"
  ALT_HEADER="# --- Backend runs on the SAME machine as Ollama (uvicorn on host) ---"
  ALT_API_V1="${API_V1}"
else
  DEFAULT_API_V1="${API_V1}"
  ALT_HEADER="# --- If the API runs in Docker and Ollama is on the host ---"
  ALT_API_V1="${DOCKER_API_V1}"
fi

cat > "$OUT_SNIPPET" <<EOF
# --- Generated by scripts/setup-local-llm.sh at $(date -Iseconds) ---
# Repo: ${REPO_ROOT}
# Merge these into your .env (or paste into your secrets manager). Do not commit .env.
SENTINELOPS_LLM_OLLAMA=1
OPENAI_API_KEY=ollama
SENTINELOPS_LLM_BASE_URL=${DEFAULT_API_V1}
SENTINELOPS_LLM_DRAFT_MODEL=${DRAFT_TAG}
SENTINELOPS_LLM_MODEL=${REFINE_TAG}
SENTINELOPS_LLM_CASCADE=1
#
${ALT_HEADER}
# SENTINELOPS_LLM_BASE_URL=${ALT_API_V1}
# (Linux Docker: keep extra_hosts: - "host.docker.internal:host-gateway" in docker-compose;
#  also bind Ollama on 0.0.0.0 — see scripts/bind-ollama-host.sh.)
EOF

log "Wrote snippet: $OUT_SNIPPET"
log "Next: append that file to your .env, restart the backend, open /vapt and run 'Generate triage'."
log "Log file: $LOG"
exit 0
